name: screener
type: app
base: core18
version: '1.0.3'
summary: Linux app for easy screenshot
description: |
  * Selection area
  * Selection area delay
  * Desktop
  * Search screenshot in Google
  * Cloud Vision (select text from screenshot)
  * Cloud Translate (translate select text from screenshot)
  * Save image in buffer
  * Save image in imgur

grade: stable
confinement: strict

parts:
  screener:

    plugin: gradle
    gradle-output-dir: build/libs
    source: https://github.com/keygenqt/screener.git
    source-type: git
    source-tag: master
    build-environment:
      - JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      - PATH: $JAVA_HOME/jre/bin:$PATH

    build-packages:
      - default-jdk
      - default-jre
      - libslf4j-java

    stage-packages:
      - default-jre

apps:
  screener:
    command: java -jar $SNAP/jar/screener.jar
    extensions:
      - gnome-3-28
    plugs:
      - home
      - network
      - unity7
